name: Publish

on:
  workflow_dispatch:

jobs:
  set-customers:
    runs-on: ubuntu-latest
    outputs:
      customers: ${{ steps.customers.outputs.customers }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: customers
      run: echo "customers=$(ls customers/ | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> ${GITHUB_OUTPUT}

  release:
    needs: set-customers
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        customer: ${{ fromJson(needs.set-customers.outputs.customers) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'customers/${{ matrix.customer }}/package-lock.json' # THIS PATTERN did the trick for me.
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci
        working-directory: customers/${{ matrix.customer }}

      - name: Build package
        run: npm run build
        working-directory: customers/${{ matrix.customer }}

      - name: Publish package
        run: |
          sed -i "s/\$VERSION/$(date +'0.%Y%m%d.%H%M%S')/g" package.json
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: customers/${{ matrix.customer }}

