name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      customers:
        description: 'Space separated customers names'
        type: string
        required: true
      env:
        description: 'Env to publish for'
        type: choice
        default: 'prod'
        required: true
        options:
          - 'prod'
          - 'test'

jobs:
  set-variables:
    runs-on: ubuntu-latest
    outputs:
      customers: ${{ steps.customers.outputs.customers }}
      env: ${{ steps.env.outputs.env }}
      version: ${{ steps.version.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: customers
      run: |
        if [ -n "${{ inputs.customers }}" ]; then
          echo "customers=$(echo "${{ inputs.customers }}" | tr -s ' ' | tr -d '\n' | jq --raw-input --slurp --compact-output 'split(" ")')" >> ${GITHUB_OUTPUT}
        else
          echo "customers=$(ls vite/customers/ | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> ${GITHUB_OUTPUT}
        fi

    - id: env
      run:
        echo "env=${{ inputs.env || 'prod' }}" >> ${GITHUB_OUTPUT}

    - id: version
      run:
        echo "version=$(date +'0.%Y%m%d.%H%M%S')" >> ${GITHUB_OUTPUT}

  release:
    needs: set-variables
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        customer: ${{ fromJson(needs.set-variables.outputs.customers) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'vite/package-lock.json'
          registry-url: 'https://npm.pkg.github.com'

      - name: Setup node auth
        run: npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

      - name: Install dependencies
        run: npm ci
        working-directory: vite

      - name: Build package
        run: env=${{ needs.set-variables.outputs.env }} customers=${{ matrix.customer }} npm run build
        working-directory: vite

      - name: Publish package
        run: ../push_tag_to_npm.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          customers: ${{ matrix.customer }}
          package_namespace: "@${{ github.repository_owner }}"
          author: ${{ github.repository_owner }}
          repository: "git+https://github.com/${{ github.repository }}"
          version: ${{ needs.set-variables.outputs.version }}
          package_name_prefix: ${{ github.event.repository.name }}-
          env: ${{ needs.set-variables.outputs.env }}
        working-directory: vite
